name: Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy project to GCP instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "."            # 현재 폴더 전체 복사
        target: "~/tasteofkorea_kisok"

    - name: SSH into GCP and deploy container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          sudo apt update && sudo apt install -y docker.io
          cd ~/tasteofkorea_kisok
          docker stop tasteofkorea || true
          docker rm tasteofkorea || true
          docker build -t tasteofkorea-image .
          docker run -d -p 80:3000 --name tasteofkorea tasteofkorea-image
